-- MySQL Script generated by MySQL Workbench
-- Mon Sep 26 16:19:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jogopda
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jogopda` ;

-- -----------------------------------------------------
-- Schema jogopda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jogopda` DEFAULT CHARACTER SET utf8 ;
USE `jogopda` ;

-- -----------------------------------------------------
-- Table `jogopda`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jogopda`.`usuario` ;

CREATE TABLE IF NOT EXISTS `jogopda`.`usuario` (
  `idusuario` INT NOT NULL,
  `data` INT NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jogopda`.`registro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jogopda`.`registro` ;

CREATE TABLE IF NOT EXISTS `jogopda`.`registro` (
  `idregistro` BIGINT(64) NOT NULL,
  `competencia` INT NOT NULL,
  `pergunta` INT NOT NULL,
  `resposta` INT NOT NULL,
  `idusuario` BIGINT(64) NOT NULL,
  PRIMARY KEY (`idregistro`),
  INDEX `registro_usuario_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `registro_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `jogopda`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;